"""Confirm .tool-versions' python/poetry pins match the poetry config.

`python` is checked against pyproject.toml's `[project] requires-python`
range; `poetry` is checked against the exact version recorded in
poetry.lock's "generated by Poetry X.Y.Z" header comment.
"""

import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
_VERSION_RE = re.compile(r"\d+(?:\.\d+)*")
_CLAUSE_RE = re.compile(r"(>=|<=|==|!=|>|<)\s*(.+)")


def _parse_version(value: str) -> tuple[int, ...]:
    match = _VERSION_RE.match(value)
    if not match:
        raise ValueError(f"cannot parse version: {value!r}")
    return tuple(int(part) for part in match.group().split("."))


def _satisfies(version: str, specifier: str) -> bool:
    """Check `version` against a comma-separated PEP 440-style specifier.

    Only handles the simple `>=`/`<=`/`==`/`!=`/`>`/`<` operators on plain
    dotted-integer versions, which is all `requires-python` uses here.
    """
    parsed = _parse_version(version)
    for clause in specifier.split(","):
        match = _CLAUSE_RE.match(clause.strip())
        if not match:
            raise ValueError(f"cannot parse specifier clause: {clause!r}")
        op, target = match.group(1), _parse_version(match.group(2))
        length = max(len(parsed), len(target))
        a = parsed + (0,) * (length - len(parsed))
        b = target + (0,) * (length - len(target))
        satisfied = {
            ">=": a >= b,
            "<=": a <= b,
            "==": a == b,
            "!=": a != b,
            ">": a > b,
            "<": a < b,
        }[op]
        if not satisfied:
            return False
    return True


def _parse_tool_versions(path: Path) -> dict[str, str]:
    versions = {}
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        tool, *rest = line.split()
        if rest:
            versions[tool] = rest[0]
    return versions


def main() -> int:
    tool_versions = _parse_tool_versions(REPO_ROOT / ".tool-versions")
    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text())
    lock_path = REPO_ROOT / "poetry.lock"

    failed = False

    python_pin = tool_versions.get("python")
    requires_python = pyproject.get("project", {}).get("requires-python")
    if python_pin is None:
        print(".tool-versions: no `python` entry", file=sys.stderr)
        failed = True
    elif requires_python is None:
        print("pyproject.toml: no [project] requires-python", file=sys.stderr)
        failed = True
    elif not _satisfies(python_pin, requires_python):
        print(
            f".tool-versions pins python {python_pin}, which does not satisfy "
            f"pyproject.toml's requires-python ({requires_python})",
            file=sys.stderr,
        )
        failed = True

    poetry_pin = tool_versions.get("poetry")
    lock_header = lock_path.read_text().splitlines()[0] if lock_path.exists() else ""
    lock_match = re.search(r"generated by Poetry (\S+)", lock_header)
    lock_poetry_version = lock_match.group(1) if lock_match else None
    if poetry_pin is None:
        print(".tool-versions: no `poetry` entry", file=sys.stderr)
        failed = True
    elif lock_poetry_version is None:
        print("poetry.lock: could not find a 'generated by Poetry X.Y.Z' header", file=sys.stderr)
        failed = True
    elif poetry_pin != lock_poetry_version:
        print(
            f".tool-versions pins poetry {poetry_pin}, but poetry.lock was generated by "
            f"Poetry {lock_poetry_version} — run `poetry lock` with the pinned version "
            "installed, or update .tool-versions to match",
            file=sys.stderr,
        )
        failed = True

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
